/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIdRouteImport } from './routes/studio/$id'
import { Route as RecordingIdRouteImport } from './routes/recording/$id'
import { Route as DemoIdRouteImport } from './routes/demo/$id'
import { Route as ApiRecordingsRouteImport } from './routes/api/recordings'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiGenerateTourRouteImport } from './routes/api/generate-tour'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingIdRoute = RecordingIdRouteImport.update({
  id: '/recording/$id',
  path: '/recording/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordingsRoute = ApiRecordingsRouteImport.update({
  id: '/api/recordings',
  path: '/api/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateTourRoute = ApiGenerateTourRouteImport.update({
  id: '/api/generate-tour',
  path: '/api/generate-tour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/signals': typeof SignalsRoute
  '/api/generate-tour': typeof ApiGenerateTourRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/recordings': typeof ApiRecordingsRoute
  '/demo/$id': typeof DemoIdRoute
  '/recording/$id': typeof RecordingIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/signals': typeof SignalsRoute
  '/api/generate-tour': typeof ApiGenerateTourRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/recordings': typeof ApiRecordingsRoute
  '/demo/$id': typeof DemoIdRoute
  '/recording/$id': typeof RecordingIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/signals': typeof SignalsRoute
  '/api/generate-tour': typeof ApiGenerateTourRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/recordings': typeof ApiRecordingsRoute
  '/demo/$id': typeof DemoIdRoute
  '/recording/$id': typeof RecordingIdRoute
  '/studio/$id': typeof StudioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/dashboard'
    | '/landing'
    | '/signals'
    | '/api/generate-tour'
    | '/api/leads'
    | '/api/recordings'
    | '/demo/$id'
    | '/recording/$id'
    | '/studio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/dashboard'
    | '/landing'
    | '/signals'
    | '/api/generate-tour'
    | '/api/leads'
    | '/api/recordings'
    | '/demo/$id'
    | '/recording/$id'
    | '/studio/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/dashboard'
    | '/landing'
    | '/signals'
    | '/api/generate-tour'
    | '/api/leads'
    | '/api/recordings'
    | '/demo/$id'
    | '/recording/$id'
    | '/studio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  SignalsRoute: typeof SignalsRoute
  ApiGenerateTourRoute: typeof ApiGenerateTourRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiRecordingsRoute: typeof ApiRecordingsRoute
  DemoIdRoute: typeof DemoIdRoute
  RecordingIdRoute: typeof RecordingIdRoute
  StudioIdRoute: typeof StudioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording/$id': {
      id: '/recording/$id'
      path: '/recording/$id'
      fullPath: '/recording/$id'
      preLoaderRoute: typeof RecordingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recordings': {
      id: '/api/recordings'
      path: '/api/recordings'
      fullPath: '/api/recordings'
      preLoaderRoute: typeof ApiRecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-tour': {
      id: '/api/generate-tour'
      path: '/api/generate-tour'
      fullPath: '/api/generate-tour'
      preLoaderRoute: typeof ApiGenerateTourRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  SignalsRoute: SignalsRoute,
  ApiGenerateTourRoute: ApiGenerateTourRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiRecordingsRoute: ApiRecordingsRoute,
  DemoIdRoute: DemoIdRoute,
  RecordingIdRoute: RecordingIdRoute,
  StudioIdRoute: StudioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
